### ISSUE TITLE
How to Use Zsh (or Another Shell) ?

### ISSUE THREAD

**Issue by pad92** [replicajune/survive-on-windows#4]
cmd from cmd `wsl zsh` for launch zsh without using bash :)

**Comment by replicajune** [comment]
I'm not going this deep. I'm guessing that if you're using zsh you'll know your way around wsl to change that ?
Choice of shell is great but It's probably out of the scope of this repository. It is the same reason I didn't elaborate much on the wsl flavor.

if there a big difference setting zsh over wsl ?
